import type { Paper } from './types'

export const AMAZON_TALKS: Paper[] = [
  {
    id: 'amz-imageragturbo',
    title: 'ImageRAGTurbo: Towards One-step Text-to-Image Generation with Retrieval-Augmented Diffusion Models',
    shortTitle: 'ImageRAGTurbo',
    authors: ['Peijie Qiu', 'Hariharan Ramshankar', 'Arnau Ramisa', 'Amit Kumar K. C.', 'Rene Vidal', 'Vamsi Salaka', 'Rahul Bhagat'],
    firstAuthor: 'Peijie Qiu',
    abstract: 'We propose ImageRAGTurbo, a one-step text-to-image generation method that combines retrieval-augmented generation with diffusion models. By retrieving relevant images at inference time and conditioning the diffusion process on them, we achieve high-quality synthesis in a single forward pass, dramatically reducing latency while preserving semantic fidelity.',
    session: 'Amazon Science @ CVPR 2026 | Generative Models',
    cvfUrl: 'https://cvpr.thecvf.com/virtual/2026/poster/38676',
    pdfUrl: 'https://www.amazon.science/publications/imageragturbo-towards-one-step-text-to-image-generation-with-retrieval-augmented-diffusion-models',
    videoUrl: 'https://www.youtube.com/embed/ZepbimY2yIs',
    accentColor: '#ff9900',
  },
  {
    id: 'amz-cot-video',
    title: 'Reinforcing Structured Chain-of-Thought for Video Understanding',
    shortTitle: 'Structured CoT for Video Understanding',
    authors: ['Peiyao Wang', 'Haotian Xu', 'Sol Vesdapunt', 'Rui Hou', 'Jingyi Zhang', 'Haibin Ling', 'Oleksandr Obiednikov', 'Ning Zhou', 'Kah Kuen Fu'],
    firstAuthor: 'Peiyao Wang',
    abstract: 'We introduce a reinforcement learning framework that trains video understanding models to produce structured chain-of-thought reasoning. By explicitly rewarding coherent temporal and causal reasoning chains, our approach significantly improves performance on complex video QA benchmarks while making model decisions more interpretable.',
    session: 'Amazon Science @ CVPR 2026 | Video Understanding',
    cvfUrl: 'https://cvpr.thecvf.com/virtual/2026/poster/36512',
    pdfUrl: 'https://www.amazon.science/publications/reinforcing-structured-chain-of-thought-for-video-understanding',
    videoUrl: 'https://www.youtube.com/embed/rXT7YafJINg',
    accentColor: '#ff9900',
  },
  {
    id: 'amz-model-stitching',
    title: 'Revisiting Model Stitching in the Foundation Model Era',
    shortTitle: 'Revisiting Model Stitching',
    authors: ['Zheda Mai', 'Ke Zhang', 'Fu-En Wang', 'Zixiao Ken Wang', 'Albert Y. C. Chen', 'Lu Xia', 'Min Sun', 'Wei-Lun Chao', 'Cheng-Hao Kuo'],
    firstAuthor: 'Zheda Mai',
    abstract: 'We revisit model stitching—combining intermediate representations from separately trained networks—in the context of large foundation models. We show that modern foundation models enable much more effective stitching than previously possible, allowing practitioners to mix encoder and decoder components across architectures and modalities with minimal fine-tuning.',
    session: 'Amazon Science @ CVPR 2026 | Foundation Models',
    cvfUrl: 'https://cvpr.thecvf.com/virtual/2026/poster/38586',
    pdfUrl: 'https://www.amazon.science/publications/revisiting-model-stitching-in-the-foundation-model-era',
    videoUrl: 'https://www.youtube.com/embed/i6-Vn51tk78',
    accentColor: '#ff9900',
  },
  {
    id: 'amz-rmir',
    title: 'RMIR: A Benchmark Dataset for Reasoning-Intensive Multimodal Image Retrieval',
    shortTitle: 'RMIR Benchmark',
    authors: ['Yijiang Li', 'Kunal Kotian', 'Ali Marjaninejad', 'Meir Friedenberg', 'Kaushik Pavani', 'Sunny Dasgupta'],
    firstAuthor: 'Yijiang Li',
    abstract: 'We introduce RMIR, a new benchmark for multimodal image retrieval that specifically targets queries requiring complex multi-step reasoning over both image content and textual descriptions. Unlike existing retrieval benchmarks, RMIR requires models to perform relational, compositional, and causal reasoning to identify correct matches, exposing significant gaps in current vision-language retrieval systems.',
    session: 'Amazon Science @ CVPR 2026 | Multimodal Retrieval',
    cvfUrl: 'https://cvpr.thecvf.com/virtual/2026/poster/38920',
    pdfUrl: 'https://www.amazon.science/publications/rmir-a-benchmark-dataset-for-reasoning-intensive-multimodal-image-retrieval',
    videoUrl: 'https://www.youtube.com/embed/Uqitvyw9WHo',
    accentColor: '#ff9900',
  },
  {
    id: 'amz-image-clustering',
    title: 'Universal Guideline-Driven Image Clustering via a Hybrid LLM Agent',
    shortTitle: 'Universal Image Clustering',
    authors: ['Wenliang Zhong', 'Rob Barton', 'Lucas Goncalves', 'Kushal Kumar', 'Feng Jiang', 'Hehuan Ma', 'Yuzhi Guo', 'Vidit Bansal', 'Karim Bouyarmane', 'Junzhou Huang'],
    firstAuthor: 'Wenliang Zhong',
    abstract: 'We present a universal image clustering framework driven by natural-language guidelines and powered by a hybrid LLM agent. Rather than optimising a fixed objective, our system accepts arbitrary user-defined criteria (e.g., cluster by depicted activity vs. by scene type) and uses LLM-guided proposal and refinement to produce guideline-compliant clusters without retraining.',
    session: 'Amazon Science @ CVPR 2026 | Clustering & Representation',
    cvfUrl: 'https://cvpr.thecvf.com/virtual/2026/poster/37785',
    pdfUrl: 'https://www.amazon.science/publications/universal-guideline-driven-image-clustering-via-a-hybrid-llm-agent',
    videoUrl: 'https://www.youtube.com/embed/r3x3b7KDnqM',
    accentColor: '#ff9900',
  },
  {
    id: 'amz-visual-grounding',
    title: 'Visual Grounding for Object Questions',
    shortTitle: 'Visual Grounding for Object Questions',
    authors: ['Martin Nicolas Everaert', 'Hiro Takeda', 'Xiruo Liu', 'Vivek Yadav', 'Vidya Narayanan', 'Raja Bala'],
    firstAuthor: 'Martin Everaert',
    abstract: 'We address visual grounding for object questions—the task of precisely localising image regions that answer natural-language questions about objects. We introduce a two-stage approach that first identifies candidate objects via language-driven attention, then refines bounding-box predictions using cross-modal reasoning, achieving state-of-the-art grounding accuracy on multiple benchmarks.',
    session: 'Amazon Science @ CVPR 2026 | Visual Grounding',
    cvfUrl: 'https://cvpr.thecvf.com/virtual/2026/poster/38604',
    pdfUrl: 'https://www.amazon.science/publications/visual-grounding-for-object-questions',
    videoUrl: 'https://www.youtube.com/embed/YPrNK54A32c',
    accentColor: '#ff9900',
  },
]
